# MATH 405/607 

# Numerical Methods for Differential Equations

[[Instructor: Christoph Ortner]](http://www.math.ubc.ca/~ortner/)  [[CANVAS]](https://canvas.ubc.ca/courses/55324)


## Linear Systems

* arrays
* vectors and matrices
* linear systems in matrix form
* backsubstitution
* Gaussian elimination 
* LU factorisation
* sparse matrices
* banded matrices 
* Eigendecomposition

In [3]:
include("../math405.jl")

 Activating environment at `~/Documents/UBC/Math/Math 405/math405_2020W/Project.toml`


* https://fncbook.github.io/fnc/linsys/overview.html // reccomended for everyone
* https://github.com/ettersi/ComputationalMathematics/blob/master/03_lu_factorisation.pdf
* E. Süli and D. Mayer, An Introduction to Numerical Analysis, Ch. 2
* G. H. Golub and C. F. Van Loan. Matrix Computations. 1996
* L. N. Trefethen and D. Bau. Numerical Linear Algebra. 1997
* N. J. Higham. Accuracy and Stability of Numerical Algorithms. 2002 

## Background 

I will assume that you are familiar with symbolic linear algebra, in particular: 
* The vector spaces $\mathbb{R}^N, \mathbb{C}^N$
* If we don't want to specify which field we are considering we will write $\mathbb{F}$
* Matrices $A \in \mathbb{F}^{N \times M}$
* Standard matrix algebra, such as $A * B, A+\lambda B, A*x$, etc.
* Matrices are representations of linear operators
* Writing linear systems in matrix form 
* Gaussian elimination for solving linear systems

If you feel you are missing this background, then please find some suitable lecture notes.

In `Julia` we can create and manipulate matrices and vectors as follows:
* https://docs.julialang.org/en/v1/manual/arrays/
* https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/

In [2]:
x = rand(3)       # vector with random entries

3-element Array{Float64,1}:
 0.9170045282035915
 0.768880118743648
 0.0033841710289770344

In [10]:
A = rand(3, 3)   # 3 x 3 matrix with random entries

3×3 Array{Float64,2}:
 0.187352  0.135617  0.167922
 0.725257  0.458663  0.6781
 0.832594  0.749268  0.0784122

In [4]:
y = A * x          # mat-vec multiplication

3-element Array{Float64,1}:
 0.45980585190505574
 0.8549202855454611
 0.8644982880296159

In [5]:
y + x              # addition 

3-element Array{Float64,1}:
 1.376810380108647
 1.623800404289109
 0.867882459058593

In [7]:
y .* x             # elementwise multiplication
# dot is very powerful! can work with any function

3-element Array{Float64,1}:
 0.4216440482914461
 0.6573312106665475
 0.00292561006095007

In [8]:
#y * x              # Warning to Matlab users : y * x is not defined 
# But you could
A = rand(3,2)
B  = rand(2,3)
A * B

3×3 Array{Float64,2}:
 0.13219   0.527286  0.361787
 0.338672  0.831399  0.518202
 0.442764  0.674888  0.353318

In [11]:
A * rand(3, 2)   # matrix-matrix multiplication

3×2 Array{Float64,2}:
 0.225511  0.207101
 0.832476  0.812073
 1.00492   0.577882

In [12]:
# construct vectors and matrices "manually"
x = [ 1.0, 2.0, 3.0 ]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [13]:
A = [ 1.0 2.0 
      3.0 4.0 ]

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

In [14]:
B = [ 1.0 2.0; 3.0 4.0 ]

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

Further Julia functions and types to work with arrays: 
* `Array` is the type, but also the constructor, e.g., `Array{Float64, 2}(undef, 10, 10)` allocates a 10 x 10 real matrix with undefined entires.
* `zeros`, `ones`, `randn`
* `A'` for adjoint; `transpose` for transpose
* `ComplexF64` for complex matrices, e.g., `rand(ComplexF64, (10,10))`
* `ldiv!, rdiv!, mul!` for efficient in-place operations
* broadcasting, e.g., `f.(A)` applies `f` to each element
* Warning: `exp(A)` is the matrix exponential, `exp.(A)` the elementwise exponential

Remark on transpose vs adjoint: $A^H = A^* = \bar{A}^T$ (i.e. transpose and complex conjugate)

Most Julia functions are well documented, you can look at the help text using `?`

In [ ]:
?randn #print docs

### Goal of this lecture: 

Direct solution of linear systems: If $A = (a_{ij})_{i,j=1}^N \in \mathbb{F}^{N \times N}, b = (b_i)_{i=1}^N \in \mathbb{F}^N$, find $x = (x_i)_{i=1}^N \in \mathbb{F}^N$ s.t.

$$\begin{aligned}
   a_{11} x_1 + a_{12} x_2 + \cdots + a_{1N} x_N &= b_1 \\ 
   a_{21} x_1 + a_{22} x_2 + \cdots + a_{2N} x_N &= b_2  \\ 
         & \qquad  \vdots \\
   a_{N1} x_1 + a_{N2} x_2 + \cdots + a_{NN} x_N &= b_N  \\ 
\end{aligned}$$


$$\begin{aligned}
   a_{11} x_1 + a_{12} x_2 + \cdots + a_{1N} x_N &= b_1 \\ 
   a_{21} x_1 + a_{22} x_2 + \cdots + a_{2N} x_N &= b_2  \\ 
         & \qquad  \vdots \\
   a_{N1} x_1 + a_{N2} x_2 + \cdots + a_{NN} x_N &= b_N  \\ 
\end{aligned}$$

$$
        \Leftrightarrow  \qquad\qquad \qquad 
    \begin{pmatrix}
        a_{11} & a_{12} &  \cdots & a_{1N}  \\ 
        a_{21} & a_{22} &  \cdots & a_{2N}  \\ 
          \vdots & \vdots &        & \vdots \\ 
        a_{N1} & a_{N2} &  \cdots & a_{NN}  \\ 
    \end{pmatrix}
    \cdot
    \begin{pmatrix}
        x_1 \\ x_2 \\ \vdots \\ x_N
    \end{pmatrix}
    = 
    \begin{pmatrix}
        b_1 \\ b_2 \\ \vdots \\ b_N
    \end{pmatrix}
$$

$$
   \Leftrightarrow \qquad \qquad  \qquad A x = b
$$

We've done this already in the intro lecture when we solved the 2-point BVP. In Julia this can be done simply via the `\` operator.

In [ ]:
A, b = rand(10,10), rand(10)    # a random linear system 
x = A \ b     # assign solution to `x`
display(x')
@show norm(A * x - b);

Behind the `\` operator is the so-called LU factorisation, which is the main goal of this lecture.

### Triangular Systems & Backward substitution

#### Example
The simplest to solve

$$\begin{aligned}
    4 x_1 + x_2 - 2 x_3 &=  3 \\ 
          2 x_2 - x_3&= 4 \\ 
                   3 x_3 &= 6      
\end{aligned}$$

$$\begin{aligned}
   x_3 &= 2 \\ 
   x_2 &= 4 + x_3/2 =?\\ 
   x_1 &= 3 + x_2 + 4 x_3 = 1
\end{aligned}$$
FIX THIS

### General Case

$$\begin{aligned}
    a_{11} x_1 + \cdots + a_{1,N-1} x_{N-1} + a_{1N} x_N &= b_1 \\ 
    & \vdots \\ 
    a_{N-1,N-1} x_{N-1} + a_{N-1,N} x_N &= b_{N-1} \\ 
    a_{NN} x_N &= b_N 
\end{aligned}$$

corresponds to $A x = b$ where $A$ is *UPPER TRIANGULAR*: 

$$
  A = \begin{pmatrix}
      * & * &  \cdots & * &  * \\ 
        & * &  \cdots & * &  * \\ 
        &   &  \ddots   & & \vdots \\ 
        &   &         & *  &  *  \\ 
        &   &          &    & * 
  \end{pmatrix}
$$

$$\begin{aligned}
    a_{11} x_1 + \cdots + a_{1,N-1} x_{N-1} + a_{1N} x_N &= b_1 \\ 
    & \vdots \\ 
    a_{N-1,N-1} x_{N-1} + a_{N-1,N} x_N &= b_{N-1} \\ 
    a_{NN} x_N &= b_N 
\end{aligned}$$

```
FOR columns n = N, N-1, ..., 1 DO
   x[n] = ( b[n] - sum( A[n, m] * x[m] for m = n+1:N ) ) / A[n,n]
END
```

In [ ]:
function backsubstitution(A::UpperTriangular, b::AbstractVector)
    N = length(b)
    x = zeros(N)
    x[N] = b[N] / A[N,N]
    for n = N-1:-1:1 
        x[n] = (b[n] - sum(A[n,m]*x[m] for m=n+1:N)) / A[n,n]
    end
    return x
end 

In [ ]:
A = UpperTriangular(rand(10,10))
b = rand(10)
x = backsubstitution(A, b)
println("Residual: ||A*x-b|| = $(norm(A*x-b))")

### Performance Analysis

```
FOR columns n = N, N-1, ..., 1 DO
   x[n] = ( b[n] - sum( A[n, m] * x[m] for m = n+1:N ) ) / A[n,n]
END
```

$$
  \#{\rm FLOPS} \approx 1 + 2 + 3 + \dots + N \approx N^2
$$

We will say that "backsubstituation requires $O(N^2)$ operations. This is the same cost as a matrix-vector multiplication, but much cheaper than a matrix-matrix multiplication $O(N^3)$.

### Remark on Julia performance

Julia is an incredibly "democratic" language. Similar to C, C++, Fortran, 
etc but very different from Python or Matlab, well-written user code in Julia 
can be just as fast as core library code. Our code here is not very well-written
but it still gets into an ok performance ball-park.

In [ ]:
using BenchmarkTools
N = 10; A = UpperTriangular(rand(N,N)); b = rand(N)
print("  Our toy code:" ); @btime backsubstitution($A, $b)
print("Julia built-in:" ); @btime ($A\$b)
;

### Gaussian Elimination

We now return to *full* systems, $A x = b$ where $A \in \mathbb{F}^{N \times N}, b \in \mathbb{F}^N$. Our goal is to reduce their solution to backsubstitution. This is achieved by performing Gaussian elimination but remembering the operations:

#### Example

$$
\begin{pmatrix}
   3 &  -1 & 2 \\ 
   1 & 2 & 3 \\ 
   2 & -2 & -1 
\end{pmatrix}
\cdot 
\begin{pmatrix}
  x_1 \\ x_2 \\ x_3 
\end{pmatrix}
= 
\begin{pmatrix}
 12 \\ 11 \\ 2 
\end{pmatrix} 
$$

$$
\begin{pmatrix}
   3 &  -1 & 2 \\ 
   1 & 2 & 3 \\ 
   2 & -2 & -1 
\end{pmatrix}
\cdot 
\begin{pmatrix}
  x_1 \\ x_2 \\ x_3 
\end{pmatrix}
= 
\begin{pmatrix}
 12 \\ 11 \\ 2 
\end{pmatrix}
$$
* row[2] $\leftarrow$ row[2] - $\frac{1}{3}$ row[1]
* row[3] $\leftarrow$ row[3] - $\frac{2}{3}$ row[1]

$$
\begin{pmatrix}
   3 &  -1 & 2 \\ 
   0 & 7/3 & 7/3 \\ 
   0 & -4/3 & -7/3 
\end{pmatrix}
\cdot 
\begin{pmatrix}
  x_1 \\ x_2 \\ x_3 
\end{pmatrix}
= 
\begin{pmatrix}
 12 \\ 7 \\ -6
\end{pmatrix} 
$$

$$
\begin{pmatrix}
   3 &  -1 & 2 \\ 
   0 & 7/3 & 7/3 \\ 
   0 & -4/3 & -7/3 
\end{pmatrix}
\cdot 
\begin{pmatrix}
  x_1 \\ x_2 \\ x_3 
\end{pmatrix}
= 
\begin{pmatrix}
 12 \\ 7 \\ -6
\end{pmatrix} 
$$
* row[3] $\leftarrow$ row[3] + $\frac{4}{7}$ row[2]

$$
\begin{pmatrix}
   3 &  -1 & 2 \\ 
   0 & 7/3 & 7/3 \\ 
   0 & 0 & -1 
\end{pmatrix}
\cdot 
\begin{pmatrix}
  x_1 \\ x_2 \\ x_3 
\end{pmatrix}
= 
\begin{pmatrix}
 12 \\ 7 \\ -2
\end{pmatrix} 
$$
We have obtained an upper triangular system which we can now solve via backsubstitution!

The Gaussian elimination steps are *linear operations* and can therefore be represented as a matrix multiplication:

In [15]:
A = [ 3 -1  2 
      1  2  3 
      2 -2 -1 ]

3×3 Array{Int64,2}:
 3  -1   2
 1   2   3
 2  -2  -1

In [16]:
L1i = [ 1     0 0
        -1/3  1 0 
        -2/3  0 1 ]

L1i * A

3×3 Array{Float64,2}:
 3.0  -1.0       2.0
 0.0   2.33333   2.33333
 0.0  -1.33333  -2.33333

In [17]:
L1i * A

3×3 Array{Float64,2}:
 3.0  -1.0       2.0
 0.0   2.33333   2.33333
 0.0  -1.33333  -2.33333

In [18]:
L2i = [ 1  0  0 
        0  1  0 
        0 4/7 1]
U = L2i * L1i *  A 

3×3 Array{Float64,2}:
 3.0          -1.0       2.0
 0.0           2.33333   2.33333
 2.22045e-16   0.0      -1.0

We are now very close to an LU factorisation: 
$$
   U := L_2^{-1} L_1^{-1} A
$$
is upper triangular. 

Now observe that 
$$
\begin{pmatrix}
    1 &  &  \\ 
    -l_{21} & 1 &  \\ 
    -l_{31}  & 0 &  1 
\end{pmatrix}^{-1} 
= 
\begin{pmatrix}
    1 &  &  \\ 
    l_{21} & 1 &  \\ 
    l_{31}  & 0 &  1 
\end{pmatrix} 
$$
and analogously for all $L_n^{-1}$-matrices. True for allLT matrices with 1s on diagonal

Take $L = L_1 L_2 = (L_2^{-1} L_1^{-1})^{-1}$ then we have 
$$ 
  L = 
\begin{pmatrix}
    1 &  &  \\ 
    l_{21} & 1 &  \\ 
    l_{31}  & 0 &  1 
\end{pmatrix}
\cdot 
\begin{pmatrix}
    1 &  &  \\ 
    0 & 1 &  \\ 
    0  & l_{32} &  1 
\end{pmatrix}
= 
\begin{pmatrix}
    1 &  &  \\ 
    l_{21} & 1 &  \\ 
    l_{31}  & l_{32} &  1 
\end{pmatrix}
$$

In [20]:
Li =  L2i * L1i 
L = inv(Li)

3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.333333   1.0       0.0
 0.666667  -0.571429  1.0

In [21]:
# check that we haven't made a mess! -> now, we have an LU factorisation
L * U - A

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

## LU Factorisation 

**Theorem:** If $A$ is non-singular then there exist
* a permuation matrix $P$ 
* a lower triangular matrix $L$
* and an upper triangular matrix $U$
such that 
$$
    P A = LU
$$

*Proof:* see e.g. Süli & Mayers, §4.2. 

### Why the Permutation Matrix?

To prevent division by zero 
$$ 
   A = 
   \begin{pmatrix}
       0 & b \\ 
       a & c
   \end{pmatrix}
$$
Cannot eliminate $a_{21}$. Instead: 
$$ 
   P A = 
   \begin{pmatrix}
       0 & 1 \\ 
       1 & 0
   \end{pmatrix}
    \cdot 
   \begin{pmatrix}
       0 & b \\ 
       a & c
   \end{pmatrix}
    = 
   \begin{pmatrix}
       a & c \\ 
       0 & b
   \end{pmatrix}   
$$
This is called (partial) *pivoting*! The matrix $P$ is never stored, this is just a convenient way to write permutations in the language of linear algebra.  (See also *complete pivoting* which is almost never used!)

... but also for numerical stability. (cf. Workshops!) E.g. if 
$$
   A = 
   \begin{pmatrix}
       \epsilon & b \\ 
       a & c
   \end{pmatrix}
$$
Then 
$$
    L = 
   \begin{pmatrix}
       1 & 0 \\ 
       a/\epsilon & 1
   \end{pmatrix},
    \qquad \qquad
    U = 
   \begin{pmatrix}
       \epsilon & b \\ 
        0 & c - v/\epsilon
   \end{pmatrix}    
$$

But with pivoting: (assuming $a \gg \epsilon$)
$$ 
    P = 
   \begin{pmatrix}
       0 & 1 \\ 
       1 & 0
    \end{pmatrix},
    \qquad \qquad 
    %
    L = 
   \begin{pmatrix}
       1 & 0 \\ 
       \epsilon/a & 1
    \end{pmatrix},    
    %
    \qquad \qquad 
    U = 
   \begin{pmatrix}
       a & c \\ 
       0 & b - c/a
    \end{pmatrix}.
$$

### Sparse matrices

**Loose Definition:** A matrix $A \in \mathbb{F}^{N \times M}$ is called *sparse* if the number of non-zero entries is much smaller than $NM$. We will encounter sparse matrices when we cover PDEs, but see also [Sparse Arrays Documentation](https://docs.julialang.org/en/v1/stdlib/SparseArrays/)

For example, in our opening lecture we enountered the tri-diagonal matrices
$$
    A = 
    \begin{pmatrix} 
        a_{11} & a_{12} &   &  & & \\ 
        a_{21} & a_{22} & a_{23} & &  & \\ 
               & a_{32} & a_{33} & a_{34}  &   &  \\ 
               &        &  \ddots & \ddots & \ddots & 
    \end{pmatrix}
$$
In this case the $A = LU$ factorisation can be performed in $O(N)$ operations as long as no pivoting is required! (see exercises/workshops)

This is a special case of [*banded matrices*](https://en.wikipedia.org/wiki/Band_matrix); see also [BandedMatrices.jl](https://github.com/JuliaMatrices/BandedMatrices.jl).

### Conditioning 

We consider again a linear system 
$$ 
 A x = b 
$$
But let us now assume that the right-hand side $b$ has an error, i.e. the "real" system which we don't know is 
$$
 A \tilde{x} = \tilde{b}
$$
How close are $x$ and $\tilde{x}$?

First things first: What do we mean by "close"? There is no single correct definition, it is problem-dependent. But in the absence of a specific problem, in our general setting let us just assume that there is some norm $\|\cdot\|$ defined on $\mathbb{F}^N$. Then we can ask how large is the error $\| x - \tilde{x}\|$? 

$$\begin{aligned}
    A (x - \tilde x) &= b - \tilde b \\ 
    \| x -  \tilde x \| &= \| A^{-1} (b -  \tilde b) \| 
\end{aligned}$$

But this is too explicit; we want something more generic ... 

The matrix-norm: 
$$ 
    \| A \| := \sup_{x \neq 0} \frac{ \| A x \|}{\|x\|} 
         = \sup_{\|x \| =  1} \|Ax\|
$$

Then we obtain 
$$
    \| x - \tilde x\| \leq \| A^{-1} \| \| b - \tilde b\|
$$ 

Now the relative error:  $A \tilde x = \tilde b$, 
$$ 
    \| \tilde b \| \leq \|A \| \, \|\tilde x \| 
$$

$$
    \frac{\| x - \tilde x\|}{\|\tilde x \|} \leq \frac{\| A^{-1} \| \| b - \tilde b\|}{ \| \tilde x \| }
    \leq \| A \| \, \| A^{-1} \| \frac{\|b - \tilde b \|}{\| \tilde b\|}.
$$ 

**Definition:** $\kappa(A) := \|A\| \| A^{-1} \|$. Note that this definition is norm-dependent. If a norm is not explicitly specified then we normally understand $\|\cdot\| = \|\cdot\|_2$

**Proposition:** 
$$ 
        \frac{\| x - \tilde x\|}{\|\tilde x \|} \leq 
        \kappa(A) 
        \frac{\|b - \tilde b \|}{\| \tilde b\|}
$$

In Julia we can use the function `cond` to compute the condition number. 

## Other Useful Factorisations

* Cholesky Factorisations: $A = L L^*$ for hermitian positive definite matrices  (Julia: `cholesky`)
* LDL factorisation: $A = L D L^*$ for hermitian matrices (Julia: `ldlt`)
* QR factorisation: $A = Q R$ with $Q$ orthogonal, $R$ upper triangular, for solving least-squares systems (Julia: `qr`)
* singular value decomposition: $A = U \Sigma V^*$  (Julia: `svd`) 
* eigen decomposition: $A = V \Lambda V^{-1}$  (Julia: `eigen`)

[... and many others ...](https://en.wikipedia.org/wiki/Matrix_decomposition)

### Quick Review of the Eigendecomposition

Let $A \in \mathbb{C}^{N \times N}$ then with say $(\lambda, v) \in \mathbb{C} \times \mathbb{C}^N$ is an eigen-pair (eigenvalue, eigenvector) of $A$ if 

$$
    A v = \lambda v
$$

The set of eigenvalues is called the spectrum of $A$ and denoted $\sigma(A)$.

* If $(\lambda_i, v_i)$ are eigenpairs and $\lambda_i$ distinct, then the $v_i$ are linearly independent.
* In particular if $A$ has $N$ distinct eigenvalues, $\lambda_1, \dots, \lambda_N$ then 
$$
    A = V \Lambda V^{-1}, \qquad \Lambda = {\rm diag}(\lambda_i), \quad V = [v_1 \dots v_N].
$$
This is called the eigendecomposition. 

In general, if there exists an invertible $V \in \mathbb{C}^{N \times N}$ and a diagonal $\Lambda$ such that $A = V \Lambda V^{-1}$ then we say that $A$ is diagonalisable.

In [2]:
A = rand(100, 100)
F = eigen(A)
# extract the first eigenpair
λ1 = F.values[1]
v1 = F.vectors[:,1]
norm(A * v1 - λ1 * v1)

LoadError: UndefVarError: eigen not defined

In [1]:
# Or we can compute A * V - V * Λ
norm(A * F.vectors - F.vectors * Diagonal(F.values))

LoadError: UndefVarError: F not defined

We will often encounter real symmetric matrices, which have a very nice property: 

**Proposition:** 
* If $A \in \mathbb{R}^{N \times N}$ is symmetric, or $A \in \mathbb{C}^{N \times N}$ is hermitian, then $A$ has real eigenvalues and orthogonal eigenvectors. 
* Equivalently, $A = Q \Lambda Q^T$ with $\Lambda = {\rm diag}(\lambda_i)$, $\lambda_i \in \mathbb{R}$ and $Q^T Q = Q Q^T = I$.
* Equivalently, there exists an orthonormal basis $\{q_n\}$ of $\mathbb{R}^N$ and $\lambda_n \in \mathbb{R}$ such that 
 $$
     A = \sum_{n = 1}^N \lambda_n q_n q_n^*
 $$
 
 Proof: see recorded lecture

**Definition:** More generally we call a matrix $A \in \mathbb{C}^{N \times N}$ *normal* if $A = Q \Lambda Q^*$ with $\Lambda$ complex diagonal and $Q^* Q = Q Q^* = I$; i.e., if it has a (complex) orthonormal eigenbasis (the columns of $Q$)

In [4]:
A = rand(10, 10)
A = A + A' 
F = eigen(A)
println("σ = ", round.(F.values, digits=2))
println("||QQ' - I|| = ", norm(F.vectors * F.vectors' - I))

σ = [-1.98, -1.51, -1.1, -0.85, -0.03, -0.0, 0.58, 0.98, 1.78, 9.87]
||QQ' - I|| = 2.311800325368522e-14


**Applications:**

Let $A \in \mathbb{C}^{N \times N}$ normal, $A = Q \Lambda Q^T$, then 
* $A^{-1} = Q \Lambda^{-1} Q^T$ 
* $\| A \| = \max_n |\lambda_n|$  (cf exercise)
* $\| A^{-1} \| = \max_n |\lambda_n^{-1}| = (\min_n |\lambda_n|)^{-1}$ 
* So for the condition number we get 
$$
    \kappa(A) = \frac{\max_n |\lambda_n|}{\min_n |\lambda_n|}
$$
$\kappa = || A || \,|| A^{-1} ||$

Operator norm $\|A\| = \max_{\|x\|_2 = 1}\|Ax\|_2$

Think about it as the the maximum amount of scaling for any unit vector